[build]
  command = "yarn build docs"
  publish = "dist/docs"
  ignore = "git diff --quiet HEAD^ HEAD docs/app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "docs/functions"