name: PR Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  integrate:
    # reusable workflows repo and branch is required for pull request event
    uses: ngaox/ngaox/.github/workflows/integrate.yml@main
    with:
      ref: ${{ github.event.pull_request.head.ref }}

  build_and_preview:
    needs: integrate
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn --frozen-lockfile && yarn build:hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAOSPAD_NGAOX }}'
          projectId: chaospad-ngaox
