name: '[RE] ðŸš€ Deploy'
on:
  workflow_call:
    inputs:
      artifacts-key:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      token:
        required: true
      FIREBASE_SERVICE_ACCOUNT:
        required: true
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ngaox'
          cache: 'yarn'
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifacts-key }}
          path: dist
      - name: ðŸŽ‰ Publish packages to npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/packages
          for package in */; do
            cd $package
            npm publish --access public
            cd ..
          done
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: ðŸŽ‰ Publish packages to GPR
        env:
          NODE_AUTH_TOKEN: ${{ secrets.token }}
        run: |
          cd dist/packages
          for package in */; do
            cd $package
            npm publish --access public
            cd ..
          done
  hosting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifacts-key }}
          path: dist
      - name: ðŸŽ‰ Deploy docs & demos
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.token }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ngaox-lab
